artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Godwin45/datasets/raw/main/catsndogs.zip
  local_data_file: artifacts/data_ingestion/catsndogs.zip
  unzip_dir: artifacts/data_ingestion



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5